### PR TITLE
Fix warnings and add additional node to jenkins

### PR DESCRIPTION
**Pull request by pfultz2**

### CODE REVIEW

**Comment by pfultz2** [comment]
ok, so it looks like the hip part fails due to compiler bug. Do we want still run hip on jenkins?

**Comment by kknox** [comment]
Lets talk about it face to face on monday

**Comment by kknox** [comment]
@pfultz2 Can you document why you think it would be a good idea to call std::abort() in a library?  As a generic statement, I do not like it when a library aborts a process.

@guacamoleo I agree with all other changes.

**Comment by pfultz2** [comment]
The program is not valid at that point. It would be better to throw exception, but you guys don't handle those in the library. The library should never reach these points, but if they do, then there is a serious problem that should be fixed.

**Comment by kknox** [comment]
@pfultz2 
Can you squash these 13 commits to something around 5 commits that make the most sense?  I've also requested @guacamoleo to review.

**Comment by pfultz2** [comment]
I don't know how to squash the commits like that.

**Comment by kknox** [comment]
That's fine; would you mind if I squashed all the commits into 1 when I merge?  Github can do that automatically.

**Comment by pfultz2** [comment]
Yea sure, go ahead.

**Pull request merged**
